ProyectoCurso/urls.py
"""
Definition of urls for ProyectoCurso.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views


urlpatterns = [
    path('', views.home, name='home'),
    path('contacto/', views.contacto, name='contacto'),
    path('acercade/', views.acercade, name='acercade'),
    
    path('bloga/', views.blog, name='blogp'),
    path('blog/', views.ListarPublicacionView.as_view(extra_context={'title': 'Blog', 'year':datetime.now().year}), name='blog'),

    path('blog/est', views.blogest, name='blog_est'),
    path('blog/estudiantes', views.ListarEstudianteView.as_view(extra_context={'title': 'BlogEst', 'year':datetime.now().year}), name='blog_estudiante'),

    path('blog/car', views.bloga, name='blog_inc'),
    path('blog/carrera', views.ListarIngresarCarrera.as_view(extra_context={'title': 'BlogCar', 'year':datetime.now().year}), name='blog_ingresarcarrera'),


    path('blog/cat', views.blogb, name='blog_agregarcat'),
    path('blog/catedraticos', views.ListarIngresarCatedratico.as_view(extra_context={'title': 'BlogCat', 'year':datetime.now().year}), name='blog_agregarcatedratico'),


    path('blog/cur', views.blogc, name = 'blog_incur'),
    path('blog/cursos', views.ListarCurso.as_view(extra_context={'title': 'BlogCur', 'year':datetime.now().year}), name = 'blog_ingresarcurso'),


    path('blog/curlib', views.blogd, name = 'blog_incurlib'),
    path('blog/cursoslibres', views.ListarCursoLibre.as_view(extra_context={'title': 'BlogCurLib', 'year':datetime.now().year}), name = 'blog_ingresarcursolibre'),


    path('blog/asignacc', views.blog_asignacionA, name = 'blog_cc'),
    path('blog/asignacursocarrera', views.ListarAsignaA.as_view(extra_context={'title': 'BlogAsign', 'year':datetime.now().year}), name = 'blog_cursocarrera'),



    path('blog/asignacl', views.blog_asignacionB, name = 'blog_cl'),
    path('blog/asignacursolibre', views.ListarAsignaB.as_view(extra_context={'title': 'BlogAsignLib', 'year':datetime.now().year}), name = 'blog_cursolibre'),



    path('cursos/', views.curso, name='cursos'),    
    path('cursoslibres/', views.cursolibre, name='cursolibre'),

    path('login/',views.loginview, name='login'), 
    path('login_salir/',views.login_salir, name='login_salir'),
    path('login_guardar/',views.login_guardar, name='login_guardar'),
    path('login_registrar_guardar/',views.login_registrar_guardar, name='login_registrar_guardar'),
    path('login_registrar/',views.login_registrar, name='login_registrar'),

    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]

app/models.py
"""
Definition of models.
"""

from django.db import models

# Create your models here.
class Catedratico (models.Model):
    id_Catedratico = models.IntegerField (primary_key = True)
    nombre = models.CharField (max_length = 50)
    apellido = models.CharField (max_length = 50)
    telefono = models.IntegerField ()
    direccion = models.CharField (max_length = 100)

class Carrera (models.Model):
    id_Carrera = models.IntegerField (primary_key = True)
    nombre = models.CharField (max_length = 50)

class Curso(models.Model):
    id_Curso = models.IntegerField(primary_key = True)
    nombre = models.CharField (max_length = 50)
    horario = models.CharField (max_length = 50)
    catedratico = models.ForeignKey (Catedratico, on_delete=models.CASCADE)
    carrera = models.ForeignKey (Carrera, on_delete= models.CASCADE)

class Estudiante(models.Model):
    carnet = models.IntegerField (primary_key = True)
    nombre = models.CharField (max_length = 50)
    apellido = models.CharField (max_length = 50)
    direccion = models.CharField (max_length = 100)
    telefono = models.IntegerField ()
    carrera = models.ForeignKey (Carrera, on_delete = models.CASCADE)

class CursoLibre (models.Model):
    id_CursoLibre = models.IntegerField(primary_key = True)
    nombre = models.CharField (max_length = 50)
    horario = models.CharField (max_length = 50)
    catedratico = models.ForeignKey (Catedratico, on_delete=models.CASCADE)

class AsignacionCurso (models.Model):
    id_asignacion = models.AutoField (primary_key = True)
    estudiante = models.ForeignKey (Estudiante, on_delete = models.CASCADE)
    curso = models.ForeignKey (Curso, on_delete=models.CASCADE)

class AsignacionCursoLibre (models.Model):
    id_asignacionlibre = models.AutoField (primary_key = True)
    estudiante = models.ForeignKey (Estudiante, on_delete = models.CASCADE)
    cursolibre = models.ForeignKey (CursoLibre, on_delete=models.CASCADE)

class Login (models.Model):
    id_login = models.IntegerField (primary_key= True)
    id_estudiante = models.ForeignKey (Estudiante,on_delete=models.CASCADE, null=True)
    id_catedratico = models.ForeignKey (Catedratico,on_delete=models.CASCADE, null=True)
    contrasenia = models.CharField (max_length = 30)

class Formulario (models.Model):
    id_form = models.AutoField (primary_key = True)
    nombre = models.CharField (max_length = 50)
    email = models.EmailField ()
    mensaje = models.CharField (max_length = 350)

class Publicacion(models.Model):
    id_publicacion=models.AutoField (primary_key=True)
    titulo=models.CharField (max_length = 50)
    nombre_prof=models.CharField (max_length = 50)
    descripcion=models.CharField (max_length = 350)

app/templates/app/about-us.html
{% extends 'app/base.html' %}

{% block contenido %}
    {% load staticfiles %}
    <!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb-area bg-img" style="background-image: url({% static 'app/img/bg-img/breadcumb.jpg' %});">
        <div class="bradcumbContent">
            <h2>BIENVENIDOS</h2>
        </div>
    </div>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### About Us Area Start ##### -->
    <section class="about-us-area mt-50 section-padding-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading text-center mx-auto wow fadeInUp" data-wow-delay="300ms">
                        <h3>COLEGIO PLANETA MUSICAL</h3><BR>
                        <span>"Somos Una Familia, Somos Planeta Musical" </span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-6 wow fadeInUp" data-wow-delay="400ms">
                    <p><H5> NUESTRA MISIÓN</H5>
                        Somos un grupo de profesionales del arte de la música,
                        constituidos en una academia, con la finalidad de educar 
                        musicalmente a la población marquense a través de cursos
                        aplicados de música con especialización en un instrumento musical,
                        con eficiencia y eficacia.
                    </p>
                </div>
                <div class="col-12 col-md-6 wow fadeInUp" data-wow-delay="500ms">
                    <p><H5>NUESTRA VISIÓN</H5>
                        Ser una academia líder en el ámbito musical-artístico
                        y propiciar en el Departamento de San Marcos un ambiente 
                        culto y sano con valores y actitudes de paz, 
                        a través del Arte de la Música.
                    </p>
                </div>
                 
            </div>
            
                <div class="section-heading text-center mx-auto wow fadeInUp" class="col-19" >
                    <div class="about-slides owl-carousel mt-100 wow fadeInUp" data-wow-delay="600ms">
                        <img src="{% static 'app/img/bg-img/fondo.jpg' %}" alt="Planeta musical" height="900" width="500">
                        <img src="{% static 'app/img/bg-img/fondo2.jpg' %}" alt="Planeta musical" height="900" width="900">
                        <img src="{% static 'app/img/bg-img/fondo3.jpg' %}" alt="Planeta musical" height="900" width="900">
                        <img src="{% static 'app/img/bg-img/fondo4.png' %}" alt="Planeta musical" height="900" width="900">
                    </div>
                </div>
            
                <div class="col-12 col-md-6 wow fadeInUp" data-wow-delay="500ms">
                    <p><H5> Sevicios Educativos Autorizados:</H5>                       
                             -Bachillerato en Ciencias y Letras con Orientación en Música<br>
                             -Bachillerato en Ciencias y Letras con Orientación en Artes Visuales (Diseño Gráfico, Pintura, Fotografía)<br>
                             -Bachillerato en Ciencias y Letras con Orientación en Artes Escénicas (Teatro, Actuación, Danza)<br>
                             -Técnico Profesional en Música Especializado en un Instrumento Musical. (Bajo, Guitarra, Piano, Batería)<br>
                    </p>
                </div>
                <div class="col-12 col-md-6 wow fadeInUp" data-wow-delay="500ms">
                    <p><H5> Nivel Inicial:</H5>                       
                              Este curso pretende preparar 
                              al alumno para ser instrumentista, 
                              se desarrolla de Enero a Octubre y
                              el crédito académico es un certificado
                              de Instrumentista avalado por el Ministerio de Educación                  
                    </p>
                </div>
                <div class="col-12 col-md-6 wow fadeInUp" data-wow-delay="500ms">
                    <p><H5> Nivel Intermedio:</H5>                       
                             Se desarrolla de Enero a Octubre,
                             el prerequisito es el curso         
                             nivel inicial   y      el  crédito 
                             académico es un Certificado de Instrumentista 
                             Nivel Intermedio. Avalado por el Ministerio de    Educació                
                    </p>
                </div><div class="col-12 col-md-6 wow fadeInUp" data-wow-delay="500ms">
                    <p><H5> Nivel Avanzado:</H5>                       
                             La especialidad se desarrolla de Enero a Octubre, 
                             el prerequisito es el curso del nivel intermedio 
                             y el crédito académico es un Diploma de 
                             Instrumentista Profesional, Avalado por el Ministerio de Educación.                
                    </p>
                </div>
                
            </div> 
        </div>
        
    </section>
    <!-- ##### About Us Area End ##### -->

    <!-- ##### Team Area Start ##### -->
    <section class="teachers-area section-padding-0-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading text-center mx-auto wow fadeInUp" data-wow-delay="300ms">
                        <h3>*CATEDRÁTICOS*</h3>
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- Single Teachers -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-teachers-area text-center mb-100 wow fadeInUp" data-wow-delay="400ms">
                        <!-- Thumbnail -->
                        <div class="teachers-thumbnail">
                            <img src="{% static 'app/img/bg-img/tea1.jpg' %}" alt="">
                        </div>
                        <!-- Meta Info -->
                        <div class="teachers-info mt-30">
                            <h5>Maria D. Smith</h5>
                            <span>Marketing Proffesor</span>
                        </div>
                    </div>
                </div>
                <!-- Single Teachers -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-teachers-area text-center mb-100 wow fadeInUp" data-wow-delay="500ms">
                        <!-- Thumbnail -->
                        <div class="teachers-thumbnail">
                            <img src="{% static 'app/img/bg-img/tea2.jpg' %}" alt="">
                        </div>
                        <!-- Meta Info -->
                        <div class="teachers-info mt-30">
                            <h5>Simon Duval</h5>
                            <span>Digital Proffesor</span>
                        </div>
                    </div>
                </div>
                <!-- Single Teachers -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-teachers-area text-center mb-100 wow fadeInUp" data-wow-delay="600ms">
                        <!-- Thumbnail -->
                        <div class="teachers-thumbnail">
                            <img src="{% static 'app/img/bg-img/tea3.jpg' %}" alt="">
                        </div>
                        <!-- Meta Info -->
                        <div class="teachers-info mt-30">
                            <h5>James Hogan</h5>
                            <span>HTML Proffesor</span>
                        </div>
                    </div>
                </div>
                <!-- Single Teachers -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-teachers-area text-center mb-100 wow fadeInUp" data-wow-delay="700ms">
                        <!-- Thumbnail -->
                        <div class="teachers-thumbnail">
                            <img src="{% static 'app/img/bg-img/tea4.jpg' %}" alt="">
                        </div>
                        <!-- Meta Info -->
                        <div class="teachers-info mt-30">
                            <h5>Claudia Williams</h5>
                            <span>Marketing Proffesor</span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading text-center mx-auto wow fadeInUp" data-wow-delay="300ms">
                        <h3>Universidad Mariano Gálvez de Guatemala</h3><BR>
                        <span>"Y conocereis la verdad y la verdad os hará libre" </span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-6 wow fadeInUp" data-wow-delay="400ms">
                    <p><H5>FILOSOFIA</H5>
                       La Universidad Mariano Gálvez , 
                       es una institución de educación 
                       superior, privada, independiente, 
                       no lucrativa, que funciona de acuerdo 
                       con las leyes propias de su naturaleza 
                       institucional, que fue aprobada el 
                       29 de Enero de 1966, por el Consejo 
                       Supremo Universitario de la Universidad de San Carlos de Guatemala.
                       <BR>La Universidad Mariano Gálvez reconoce el derecho de los estudiantes 
                       a organizarse libremente en asociaciones, siempre que lo hagan con 
                       el propósito de realizar actividades culturales, sociales o deportivas. 
                       Sus estatutos serán aprobados por el Consejo Directivo.
                    </p>
                </div>
                <div class="col-12 col-md-6 wow fadeInUp" data-wow-delay="500ms">
                    <p><H5>FACULTADES.</H5>
                        -ARQUITECTURA<br>
                        -CIENCIAS DE LA ADMINISTRACION<br>
                        -CIENCICAS ECONOMICAS<br>
                        -CIENCIAS JURIDICAS Y SOCIALES<br>
                        -CIENCIAS MEDICAS Y DE LA SALUD<br>
                        -HUMANIDADES<br>
                        -INGENIERIA EN SISTEMAS<br>
                        -ODONTOLOGIA<br>
                        -NUTRICION<br>
                    </p>
                </div>
                
            </div> 
        </div>
        
    </section>
    <section class="teachers-area  ">
        <div class= "container ">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading text-center mx-auto wow fadeInUp" data-wow-delay="300ms">
                       
                        <h3>CREADORES DE LA PAGINA</h3>
                         <span> Alumnos de ingenieria en sistemas </span>
                    </div>
                </div>
            </div>

            <div class="row" 'center'>
                <!-- Single Teachers -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-teachers-area text-center mb-100 wow fadeInUp" data-wow-delay="400ms">
                        <!-- Thumbnail -->
                        <div class="teachers-thumbnail">
                            <img src="{% static 'app/img/bg-img/tea1.jpg' %}" alt="">
                        </div>
                        <!-- Meta Info -->
                        <div class="teachers-info mt-30">
                            <h5>Luis Ricardo Fuentes</h5>
                           
                        </div>
                    </div>
                </div>
                <!-- Single Teachers -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-teachers-area text-center mb-100 wow fadeInUp" data-wow-delay="500ms">
                        <!-- Thumbnail -->
                        <div class="teachers-thumbnail">
                            <img src="{% static 'app/img/bg-img/tea2.jpg' %}" alt="">
                        </div>
                        <!-- Meta Info -->
                        <div class="teachers-info mt-30">
                            <h5>Jose Daniel Velasquez</h5>
                            
                        </div>
                    </div>
                </div>
                <!-- Single Teachers -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-teachers-area text-center mb-100 wow fadeInUp" data-wow-delay="600ms">
                        <!-- Thumbnail -->
                        <div class="teachers-thumbnail">
                            <img src="{% static 'app/img/bg-img/tea3.jpg' %}" alt="">
                        </div>
                        <!-- Meta Info -->
                        <div class="teachers-info mt-30">
                            <h5>Pablo Javier Miranda</h5>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </section>
    <!-- ##### Features Area Start ##### -->
{% endblock contenido %}

app/templates/app/blog_cursocarrera.html
{% extends 'app/base.html' %}

{% block contenido %}
    {% load staticfiles %}
    <!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb-area bg-img" style="background-image: url({% static 'app/img/bg-img/breadcumb.jpg' %});">
        <div class="bradcumbContent">
            <h2>Nuestro Blog</h2>
        </div>
    </div>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Blog Area Start ##### -->
    <div class="blog-area mt-50 section-padding-100">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-8">
                    <div class="academy-blog-posts">
                        <div class="row">
                        
                                <table class="table">
                                    <thead class="thead-dark">
                                        <tr>
                                        <th scope="col">No.</th>
                                        <th scope="col">Estudiante</th>
                                        <th scope="col">Curso</th>
                    
                                        </tr>
                                    </thead>
                                {% for asignacioncurso in asignacioncurso_list %}
                                <tbody>
                                        <tr>
                                            <td>{{asignacioncurso.id_asignacion}}</td>
                                            <td>{{asignacioncurso.estudiante_id}}</td>
                                            <td>{{asignacioncurso.curso_id}}</td>
                                            
                                        </tr>
                                    </tbody>
                                {% endfor %}
                                    
                                </table>
                            
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="academy-blog-sidebar">

                        <!-- Blog Post Catagories -->
                        <div class="blog-post-categories mb-30">
                            <h5>Estudiantes</h5>
                            <ul>
                                <li>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalAsignacionCurso">
                                    Asignar Curso de Carrera
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="modalAsignacionCurso" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-scrollable" role="document">
                                        <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalScrollableTitle">Curso Académico</h5>
                                            <button  type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form method="POST" action="{% url 'blog_cc' %}">
                                            {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_asignacion">ID de Asignación</label>
                                        <input type="text" class="form-control" id="id_asignacion" name="id_asignacion">
                                    </div>
                                    <div class="form-group">
                                        <label for="id_asignaestudiante">Carnet del Estudiante</label>
                                        <input type="text" class="form-control" id="id_asignaestudiante" name="id_asignaestudiante">
                                    </div>
                                    <div class="form-group">
                                        <label for="id_asignacurso">ID del Curso</label>
                                        <input type="text" class="form-control" id="id_asignacurso" name="id_asignacurso">
                                    </div>
                                        <input type="submit" class="btn btn-primary" name="Guardar">
                                    </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                        </div>
                                    </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Blog Area End ##### -->
{% endblock contenido %}

app/templates/app/blog_ingresarcursolibre.html
{% extends 'app/base.html' %}

{% block contenido %}
    {% load staticfiles %}
    <!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb-area bg-img" style="background-image: url({% static 'app/img/bg-img/breadcumb.jpg' %});">
        <div class="bradcumbContent">
            <h2>Nuestro Blog</h2>
        </div>
    </div>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Blog Area Start ##### -->
    <div class="blog-area mt-50 section-padding-100">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-8">
                    <div class="academy-blog-posts">
                        <div class="row">
                        
                                <table class="table">
                                    <thead class="thead-dark">
                                        <tr>
                                        <th scope="col">No.</th>
                                        <th scope="col">Nombre</th>
                                        <th scope="col">Horario</th>
                                        <th scope="col">Catedrático</th>
                                        
                                        </tr>
                                    </thead>
                                {% for cursolibre in cursolibre_list %}
                                <tbody>
                                        <tr>
                                            <td>{{cursolibre.id_CursoLibre}}</td>
                                            <td>{{cursolibre.nombre}}</td>
                                            <td>{{cursolibre.horario}}</td>
                                            <td>{{cursolibre.catedratico_id}}</td>
                                            
                                        </tr>
                                    </tbody>
                                {% endfor %}
                                    
                                </table>
                            
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="academy-blog-sidebar">

                        <!-- Blog Post Catagories -->
                        <div class="blog-post-categories mb-30">
                            <div class="single-latest-blog-post d-flex">
                                <div class="latest-blog-post-thumb">
                                    <img src="{% static 'app/img/blog-img/lb-4.jpg' %}" alt="">
                                </div>
                                <div class="latest-blog-post-content">
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalScrollable">
                                    Ingresar Curso Libre
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-scrollable" role="document">
                                        <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalScrollableTitle">Estudiantes</h5>
                                            <button  type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form method="POST" action="{% url 'blog_incurlib' %}">
                                            {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_cursolibre">Id de Curso Libre</label>
                                        <input type="text" class="form-control" id="id_cursolibre"  name="id_cursolibre">
                                    </div>
                                    <div class="form-group">
                                        <label for="nombre_cursolibre">Nombre del Curso</label>
                                        <input type="text" class="form-control" id="nombre_cursolibre"  name="nombre_cursolibre">
                                    </div>
                                    <div class="form-group">
                                        <label for="horario_cursolibre">Horario</label>
                                        <input type="text" class="form-control" id="horario_cursolibre"  name="horario_cursolibre">
                                    </div>
                                    <div class="form-group">
                                        <label for="catedratico_cursolibre">Id de Catedrático</label>
                                        <input type="text" class="form-control" id="catedratico_cursolibre"  name="catedratico_cursolibre">
                                    </div>
                                        <input type="submit" class="btn btn-primary" name="Guardar">
                                    </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        
                                        </div>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Blog Area End ##### -->
{% endblock contenido %}

app/templates/app/iblog_cursolibre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script type="text/javascript">
        window.location.href = "{% url 'blog_cursolibre' %}"
    </script>
</body>
</html>

app/templates/app/iblog_estudiante.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script type="text/javascript">
        window.location.href = "{% url 'blog_estudiante' %}"
    </script>
</body>
</html>